package com.example.data.analyzer

import com.example.data.parser.ImgArchiveReader
import com.example.data.parser.ImgItemEntry
import java.io.File
import java.util.Locale

/**
 * Defines the binary action to be performed on the container for an individual DFF model.
 */
enum class DffActionType {
  REPLACE,  // The model exists in the container TOC and will overwrite the existing entry
  INJECT    // The model is new and will be appended as a new entry into the container
}

/**
 * Detailed match evaluation for an individual DFF model.
 */
data class DffMatchItem(
  val fileName: String,
  val sizeBytes: Long,
  val actionType: DffActionType,
  val targetContainer: TargetContainer,
  val targetContainerFileName: String,
  val originalEntry: ImgItemEntry?,
  val sizeDiffBytes: Long
) {
  val formattedSize: String get() = ImgArchiveReader.formatFileSize(sizeBytes)
  val formattedDiff: String get() {
    if (actionType == DffActionType.INJECT) return "+$formattedSize"
    val diff = sizeDiffBytes
    return if (diff >= 0) {
      "+${ImgArchiveReader.formatFileSize(diff)}"
    } else {
      "-${ImgArchiveReader.formatFileSize(-diff)}"
    }
  }
}

/**
 * The consolidated execution plan generated by the Match Engine.
 */
data class MatchPlan(
  val items: List<DffMatchItem>,
  val affectsGta3: Boolean,
  val affectsGtaInt: Boolean,
  val replaceCount: Int,
  val injectCount: Int,
  val totalDffCount: Int,
  val statusMessage: String,
  val modName: String = "Mod"
)

/**
 * Millimeter-precise match and decision engine:
 * - Compares analyzed DFF mod models against container directory tables (TOC).
 * - Identifies with exact precision whether each model is a REPLACE or INJECT.
 * - Flags strictly which container (gta3.img, gta_int.img, or both) needs rebuild,
 *   preventing unnecessary operations on unaffected containers.
 */
object DffMatchEngine {

  fun buildMatchPlan(
    modEntries: List<ModDffEntry>,
    gameWorkingDir: File?,
    modName: String = "Mod"
  ): MatchPlan {
    if (modEntries.isEmpty()) {
      return MatchPlan(
        items = emptyList(),
        affectsGta3 = false,
        affectsGtaInt = false,
        replaceCount = 0,
        injectCount = 0,
        totalDffCount = 0,
        statusMessage = "Sin modelos DFF para procesar",
        modName = modName
      )
    }

    // 1. Read existing container TOC entries from working directory or fallback
    val gta3File = gameWorkingDir?.let { File(it, "gta3.img") } ?: File("gta3.img")
    val gtaIntFile = gameWorkingDir?.let { File(it, "gta_int.img") } ?: File("gta_int.img")

    val gta3Entries = ImgArchiveReader.readEntries(gta3File)
    val gtaIntEntries = ImgArchiveReader.readEntries(gtaIntFile)

    val gta3Map = gta3Entries.associateBy { it.name.lowercase(Locale.ROOT) }
    val gtaIntMap = gtaIntEntries.associateBy { it.name.lowercase(Locale.ROOT) }

    val matchedItems = mutableListOf<DffMatchItem>()

    for (entry in modEntries) {
      val lowerName = entry.name.lowercase(Locale.ROOT)

      // Determine match based on targetContainer preference & TOC verification
      val (targetContainer, containerFile, existingEntry, actionType) = when (entry.targetContainer) {
        TargetContainer.GTA_INT -> {
          if (lowerName in gtaIntMap) {
            val orig = gtaIntMap[lowerName]
            Quadruple(TargetContainer.GTA_INT, "gta_int.img", orig, DffActionType.REPLACE)
          } else if (lowerName in gta3Map) {
            val orig = gta3Map[lowerName]
            Quadruple(TargetContainer.GTA3, "gta3.img", orig, DffActionType.REPLACE)
          } else {
            Quadruple(TargetContainer.GTA_INT, "gta_int.img", null, DffActionType.INJECT)
          }
        }
        TargetContainer.GTA3 -> {
          if (lowerName in gta3Map) {
            val orig = gta3Map[lowerName]
            Quadruple(TargetContainer.GTA3, "gta3.img", orig, DffActionType.REPLACE)
          } else if (lowerName in gtaIntMap) {
            val orig = gtaIntMap[lowerName]
            Quadruple(TargetContainer.GTA_INT, "gta_int.img", orig, DffActionType.REPLACE)
          } else {
            Quadruple(TargetContainer.GTA3, "gta3.img", null, DffActionType.INJECT)
          }
        }
      }

      val sizeDiff = if (existingEntry != null) {
        entry.sizeBytes - existingEntry.sizeBytes
      } else {
        entry.sizeBytes
      }

      matchedItems.add(
        DffMatchItem(
          fileName = entry.name,
          sizeBytes = entry.sizeBytes,
          actionType = actionType,
          targetContainer = targetContainer,
          targetContainerFileName = containerFile,
          originalEntry = existingEntry,
          sizeDiffBytes = sizeDiff
        )
      )
    }

    val replaceCount = matchedItems.count { it.actionType == DffActionType.REPLACE }
    val injectCount = matchedItems.count { it.actionType == DffActionType.INJECT }
    val affectsGta3 = matchedItems.any { it.targetContainer == TargetContainer.GTA3 }
    val affectsGtaInt = matchedItems.any { it.targetContainer == TargetContainer.GTA_INT }

    val statusMsg = when {
      affectsGta3 && affectsGtaInt -> "Coincidencias en Exteriores (GTA3) e Interiores (GTA_INT)"
      affectsGta3 -> "Coincidencias en Exteriores (GTA3)"
      affectsGtaInt -> "Coincidencias en Interiores (GTA_INT)"
      else -> "Listo para procesar"
    }

    return MatchPlan(
      items = matchedItems,
      affectsGta3 = affectsGta3,
      affectsGtaInt = affectsGtaInt,
      replaceCount = replaceCount,
      injectCount = injectCount,
      totalDffCount = matchedItems.size,
      statusMessage = statusMsg,
      modName = modName
    )
  }

  private data class Quadruple<A, B, C, D>(val first: A, val second: B, val third: C, val fourth: D)
}
